name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: ${{ matrix.os }} / ${{ matrix.compiler }} / ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]
        include:
          - os: windows-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: gcc
          - os: macos-latest
            compiler: clang

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Fetch latest cmake + ninja.
      - uses: lukka/get-cmake@latest

      # Fetch visual studio.
      - uses: ilammy/msvc-dev-cmd@v1

      - if: ${{ runner.os == 'Linux' }}
        name: Install JUCE dependencies (Linux only)
        id: juce_dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: |
          cmake --build build
